### ISSUE TITLE
Packaging History

### ISSUE THREAD

**Issue by AnthonyHunt** [timsutton/aamporter#11]
aamporter seems to only read the first item in the <PackagingHistory> array.  Our package started life as a CS6 package which was later updated to CC than to CC2014.  Building a package list from the CCP results in only the CS6 and CC items being included an not the CC2014 items.  My packaging history is shown here.

        <PackagingHistory ID="1" BuildDate="Mon Mar 17 16:59:24 2014 ">
            <InstallInfo id="CloudPackager" version="1.4">
                <PackageName>Creative Cloud</PackageName>
                <OutputLocation>/Users/xxx/Desktop/CC</OutputLocation>
                <AAMEE_Workflow>CREATE_NEW</AAMEE_Workflow>
        </PackagingHistory>
        <PackagingHistory ID="2" BuildDate="Fri Jul 25 13:25:42 2014 ">
            <InstallInfo id="CloudPackager" version="1.5">
                <PackageName>Creative Cloud</PackageName>
                <OutputLocation>/Users/xxx/Desktop/CC</OutputLocation>
                <AAMEE_Workflow>MODIFY_EXISTING</AAMEE_Workflow>
        </PackagingHistory>
        <PackagingHistory ID="3" BuildDate="Fri Sep 26 11:10:14 2014 ">
        </PackagingHistory>
        <PackagingHistory ID="4" BuildDate="Fri Feb 20 16:53:28 2015 " BuildEpoch="1424451208">
        </PackagingHistory>
        <PackagingHistory ID="5" BuildDate="Fri Feb 20 17:03:54 2015
        </PackagingHistory>

Other history's as 2 but not included as they are identical.

Thanks,

Anthony.

**Comment by AnthonyHunt** [comment]
Obviously there's a lot of other info in each of the package history's but I've left it out as I don't think it's relevant at this stage... I can provide it securely though.

**Comment by timsutton** [comment]
If you want to e-mail it to me that would be useful.

You said that this was a package that started life as a CS6 package? I didn't even realize that CCP could take such packages as "starting points."

**Comment by AnthonyHunt** [comment]
Tim,

Did you get my email?

Ant.

**Comment by timsutton** [comment]
I didn't, no - checked my spam also. If e-mail's not working, you could also send it via something like Dropbox..

**Comment by timsutton** [comment]
Closing as this should be resolved in c0588204f8cbbc16a22f43397f038101681ff957.
