### ISSUE TITLE
Creating PLIST for Adobe Illustrator 2015

### ISSUE THREAD

**Issue by probles40** [timsutton/aamporter#16]
Hi,

I am following the directions on how to create a plist for Adobe Products, not included on the samples folder. However, every time the command "./aamporter.py --product-plist Illustrator_CC_2015.ccp" is executed, it does give this error message.
Traceback (most recent call last):
  File "./aamporter.py", line 747, in <module>
    main()
  File "./aamporter.py", line 547, in main
    if 'channels' not in plist.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
m-sus:aamporter-master admin$ ./aamporter.py --product-plist "Illustrator_CC_2015.ccp"
Traceback (most recent call last):
  File "./aamporter.py", line 747, in <module>
    main()
  File "./aamporter.py", line 547, in main
    if 'channels' not in plist.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by timsutton** [comment]
How did you create the Illustrator_CC_2015.ccp file? You should create this using the `-b` / `--build-product-plist` option, giving it the path to your CCP package's .ccp file.
