### ISSUE TITLE
aamporter.plist

### ISSUE THREAD

**Issue by elflames** [timsutton/aamporter#22]
More of a help question then a issue.

I have read the reamdme but for some reason in my state can not seem to get it to work.
For example the "local_cache_path" I am assuming is the "key" and the path to where I want the cache folder to go is a "string" ??

**Comment by timsutton** [comment]
Yes, that should be correct. If you paste your plist in here or in a gist that would help us verify.

Also, currently the plist needs to live beside the script in the same directory (a limitation I plan to remove soon).

**Comment by elflames** [comment]
All good, once I read your response I moved the plist file from the script directory inside aamporter to the same level as where the aamporter.py was located.. all good now. some reason i took the readme instructions to locate the plist inside the script directory that is the aamporter folder.
